### ISSUE TITLE
Error 259 on Windows 10

### ISSUE THREAD

**Issue by sahver** [TaylorSMarks/playsound#105]
`playsound('./sounds/iphone_ding.mp3', block=True)`

plays the sound, but also returns this error:

```
    Error 259 for command:
        play ./sounds/iphone_ding.mp3 wait
    The driver cannot recognize the specified command parameter.
```

python 3.8.12, playsound 1.3.0 on Windows 10 Pro 19043.1288

**Comment by AustinAres2007** [comment]
Format the path like this:

`playsound('.\\sounds\\iphone_ding.mp3')`

Also block is True by default.

**Comment by AustinAres2007** [comment]
Put the full path of the audio file, it may look more complicated, but I re-created your problem, and it's because it's not using the full path of the file

Example: "Z:\Documents\Code\Experimentation\program-directory\sounds\iphone_ding.mp3"

Also block is True by default, no need to specify it.

**Comment by sahver** [comment]
Thanks, the issue is solved now.

I ended up using

`playsound( os.path.abspath('./sounds/iphone_ding.mp3') )`

to go around the need to use full path as I am executing the code both from Windows and Linux.

**Comment by TaylorSMarks** [comment]
Interesting. I would like Windows and Linux to behave the same way, so if just changing the path is all it takes, the Windows version should handle that for you.

Taylor

>

**Comment by zyuerugou** [comment]
```
current_dir = os.getcwd()
input_dir = os.path.join(current_dir, 'input')
mp3_file = 'xxx.mp3'
for i in range(2):
    playsound(os.path.join(input_dir,mp3_file))
```
 I had the same problem, but I was already using the full path.
 I can play it once, but it throws an exception 259 when I need to repeat it .

python 3.10   playsound==1.3.0
