### ISSUE TITLE
How to loop sounds?

### ISSUE THREAD

**Issue by AAM1075** [TaylorSMarks/playsound#109]
playsound version: 1.2.2

I have this segment of code (Running in a new thread):

```
pathtoaudio = AppDataPath + "\\lmao.mp3"
while True:   
     print("Playing Sound...")
     playsound(pathtoaudio, block=True)
     print("Done.")
```

This code should loop the audio, but it doesn't.
The first print statement runs, but the second one doesn't print. Is this a bug?

**Comment by bbbart** [comment]
I don't know about 1.2.2, but with
* playsound 1.3.0
* on Linux
* with Python 3.10.4
the code you provided simply works as intended

**Comment by victorwss** [comment]
On windows, playsound doesn't work correctly. As far as I can tell, it works the first time you run it, but fails from the second time on.
