### ISSUE TITLE
This package depends pygobject

### ISSUE THREAD

**Issue by Granitosaurus** [TaylorSMarks/playsound#14]
Playsound depends on gnome to work on linux. In other words it needs `pygobject` package to work.

https://pygobject.readthedocs.io/en/latest/getting_started.html

**Comment by TaylorSMarks** [comment]
Sorry - I wish it didn't. If you make a PR removing any dependencies and without any regressions, I'll accept it (please uncomment out the Linux configurations in the travis.yml file, so I'll see that the code is actually getting tested.)
