### ISSUE TITLE
macOS mojave compatity

### ISSUE THREAD

**Issue by jinfagang** [TaylorSMarks/playsound#18]
there seems some issue with the newest macOS mojave:

```
File "/usr/local/lib/python3.6/site-packages/playsound.py", line 55, in _playsoundOSX
    from AppKit     import NSSound
ImportError: cannot import name 'NSSound'
```
Here is the error, should this be a compatible problem or my enviroment error?

**Comment by comeschffr** [comment]
I fixed it by doing this :
`pip3 install pyobjc`

**Comment by tcarroll2** [comment]
I keep getting this error:

File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/playsound.py", line 55, in _playsoundOSX
    from AppKit     import NSSound
ModuleNotFoundError: No module named 'AppKit'

I have installed AppKit and PyObjC via pip3.
I am using Mac OS Mojave and Python 3.7.4

**Comment by gpraceman** [comment]
Do not use pip to install AppKit.  That is a totally unrelated package.  Do an uninstall of it.  Then run the following command.

sudo pip install --upgrade --force-reinstall PyObjC PyObjC-core

**Comment by TaylorSMarks** [comment]
This is now fixed on master. I have not added PyObjC as a hard dependency, but I print out a suggestion that you aught to install it. Even without it, the code still works on Python 3 on Mac, by shelling out to Mac OS's built-in python.
