### ISSUE TITLE
Cannot play file with unicode characters in path (OSX)

### ISSUE THREAD

**Issue by skatje-myers** [TaylorSMarks/playsound#20]
`File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/playsound.py", line 67, in _playsoundOSX
    raise IOError('Unable to load sound named: ' + sound)`

Looks to be related to NSURL. Escaping the characters in the path might make it work?

**Comment by Konstantin-Ketskalo** [comment]
Using unicode characters doesn't work on Windows neither...
If full file path contains only ascii latin characters - it plays it, but using cyrillic, for instance, raises exception.
```
playsound.PlaysoundException: 
    Error 275 for command:
        open "D:\Google Диск\Programming\Python\My Programs\Miracle Morning\Counter Strike - Go Go Go!.mp3" alias playsound_0.7078874208508745
    Cannot find the specified file.  Make sure the path and filename are correct.
```
P.S. Didn't create new issue, cause it seems to be the same for different operating systems.

**Comment by colezajicek** [comment]
This can be fixed with double backslashes, or by prefixing with r

**Comment by TaylorSMarks** [comment]
This is now fixed on master. I have added in a test scenario, testBlockingSPACE_MP3, which should ensure that it doesn't regress.
