### ISSUE TITLE
Windows 10 IOError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by SavageCoder77** [TaylorSMarks/playsound#21]
The playsound function works the first time but if you use it again it gives this error IOError: [Errno 13] Permission denied. I use gtts to save an audio file name Speak.mp3 and it saves the tts right before the playsound function

**Comment by Pyroseza** [comment]
Having the same problem, the file remains opened by the module, anyway you can close the stream when finished?

**Comment by aadityadengle** [comment]
the issue has solved [here](https://github.com/aadityadengle/playsound)
