### ISSUE TITLE
No module named 'gi' 

### ISSUE THREAD

**Issue by idawud** [TaylorSMarks/playsound#24]
When I run playsound this the error i get and there seem to be no package on PyPi as 'gi' 

Traceback (most recent call last):
  File "soundplay.py", line 6, in <module>
    playsound(filename)
  File "/home/dawud/anaconda3/lib/python3.7/site-packages/playsound.py", line 91, in _playsoundNix
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by wood-j** [comment]
I got the same error too, did you solve it ? thanks

**Comment by crc8109** [comment]
> I also got the same error, but I realize that my Python's version was the 3.6 and the gi was installed on the python 3 directory, because I installed via this command "sudo apt-get install python3-gi" so I run that command on my terminal:
> 
> ln -s /usr/lib/python3/dist-packages/gi /home/your_name_goes_here/miniconda3/lib/python3.6/site-packages/
> 
> (P.S.: in "your_user_goes_here", you put your username)
> 
> And that solved the problem for me. It is also important to say that I don't realize that by myself, I searched on internet and I reached this link https://stackoverflow.com/questions/37526026/how-to-install-gi-module-for-anaconda-python3 which helped me to solve the problem. Hope you guys to solve this issue too.

You are the best Pedro!
