### ISSUE TITLE
Command to stop playback

### ISSUE THREAD

**Issue by Stick1000** [TaylorSMarks/playsound#25]
Immediately stop the specified sound.

**Comment by dorlolo** [comment]
> 立即停止指定的声音。
how to sotp? I can't find anyway....

**Comment by gpraceman** [comment]
Refer to https://developer.apple.com/documentation/appkit/nssound

**Comment by TaylorSMarks** [comment]
If you want to make a PR that adds in this feature, I'm happy to accept it as long as it doesn't add in any more dependencies or cause any regressions in the existing testcases.
