### ISSUE TITLE
Playing to a specific device

### ISSUE THREAD

**Issue by treii28** [TaylorSMarks/playsound#28]
I'm trying to play mp3 files on a raspberry pi with a DAC board installed (Seeed studio's voicecard). I might also play with bluetooth pairing. Is it possible to tell the playback to use a specific device even if it isn't set as the system default?

**Comment by TaylorSMarks** [comment]
I don’t think that’s within the scope of what I want in playsound. I want an extraordinarly simple/easy way of playing sounds from Python on Mac, Windows, and maybe Linux. Mixing in the ability to select a device would likely be a lot more complicated and be implemented in very different ways on each platform.

It may not be too terrible on macOS… I’m using the NSSound API there, which does identify a “playbackDeviceIdentifier” variable… I’m not sure what exactly I’d pass into that, but maybe it wouldn’t be too bad.

On Windows… it looks like there’s some way I can similarly give the media command interface a device identifier…

But you’re asking for Raspberry Pi specifically. Figure it out, send me a pull request, and I’ll think about merging it in. I do own a Raspberry Pi (running Raspian) so I could test it, but I’ve mainly used the Pi as a server and have never hooked it up to speakers before.

 

Taylor

**Comment by TaylorSMarks** [comment]
If you want to make a PR that adds in this feature, I'm happy to accept it as long as it doesn't add in any more dependencies or cause any regressions in the existing testcases.
