### ISSUE TITLE
Loop without Break

### ISSUE THREAD

**Issue by marcoslorhanbs** [TaylorSMarks/playsound#30]
When you call the Playsound function in a program automatically the program will "stop working" but the music stills playing, and you cannot do nothing while the music is playing like a loop.

**Comment by insolor** [comment]
On which OS / platform are you working? Also, it would be helpful if you provide sample code.

**Comment by ahmadraniri** [comment]
umm... ctrl+c on your terminal/cmd will help, may be.

**Comment by XHG78999** [comment]
OK,OK.Its a good problem.You can change the code,And Change the MCI Command(Add "repeat" after command).
I think is can help you.

**Comment by TaylorSMarks** [comment]
I don't understand the OP here. If there's a bug, please make a PR that adds in a test case to test.py demonstrating it.
