### ISSUE TITLE
Unable to delete the file after using playsound

### ISSUE THREAD

**Issue by aj-22** [TaylorSMarks/playsound#35]
I am trying to delete the file after calling playsound(filepath) on the file using os.remove(filepath). However, getting a permission error as follows:

` PermissionError                           Traceback (most recent call last)`
`<ipython-input-183-209b55787a7c> in <module>`
`----> 1 os.remove('./play/sample-m1.wav')`

`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: './play/sample-m1.wav'`

Can we modify the function so as to close/delete the open process after playback?

**Comment by Pamac** [comment]
You need to close the handle opened by calling the close method after playing so your os.remove will be allowed.


Find the winCommand function in playsound.py,
...
...
alias = 'playsound_' + str(random())
winCommand('open "' + sound + '" alias', alias)
winCommand('set', alias, 'time format milliseconds')
durationInMS = winCommand('status', alias, 'length')
winCommand('play', alias, 'from 0 to', durationInMS.decode())
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Add the two lines below
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
sleep(int(durationInMS.decode()) / 1000)
winCommand('close ', alias)
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# END OF MODIFICATIONS
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Vérified on win10...

**Comment by TaylorSMarks** [comment]
This should be solved. The "testNonBlockingRepeat" test case should ensure that a regression never occurs for this issue.
