### ISSUE TITLE
Windows 10 issues running this package

### ISSUE THREAD

**Issue by chiperiandrei** [TaylorSMarks/playsound#36]
![The image can tell you everything is goind wrong on my machine, can you help me ?](https://user-images.githubusercontent.com/44604723/64454272-3b2dd300-d0f3-11e9-8c3e-fa242995888b.png)

**Comment by rizzini** [comment]
Same here.

**Comment by XHG78999** [comment]
Try to restart the computer.It's MCI Core's BUG.I think you can report it at Microsoft Commity.

**Comment by roachsinai** [comment]
> Try to restart the computer.It's MCI Core's BUG.I think you can report it at Microsoft Commity.

Hi, if my script is very simple, like:

```
from playsound import playsound
playsound('./example.mp3')
```

it works.

But if I use it in my project in a while loop, got same error above.
