### ISSUE TITLE
play async on linux

### ISSUE THREAD

**Issue by albfan** [TaylorSMarks/playsound#38]
```
    playsound (sound, False)
  File "/usr/lib/python3.8/site-packages/playsound.py", line 80, in _playsoundNix
    raise NotImplementedError(
NotImplementedError: block=False cannot be used on this platform yet
```

Any specific issue to support it on linux?

**Comment by BlueLovin** [comment]
Same problem here...

**Comment by Unfortun3** [comment]
Still waiting ;)

**Comment by TaylorSMarks** [comment]
You’ll be waiting forever - this project is dead.

Check out the fork called boombox. Maybe they implemented it at some point.

I need to shut down the GitHub issues page for this project at some point...

Taylor

**Comment by albfan** [comment]
You can archive the repo then.

I'm succesfully using my fork #39 to play sounds on a raspberry pi
