### ISSUE TITLE
File paths with name spaces won't work (at least on Mac) in Python 3.7

### ISSUE THREAD

**Issue by paulzikopoulos** [TaylorSMarks/playsound#40]
I ran into this problem and could only solve it by placing the .wav file in a path with no spaces. It seems to be validated here: https://stackoverflow.com/questions/54179727/how-to-fix-unable-to-load-sound-error-with-python-playsound-module/54594307#54594307.

Is this an issue, is there a fix?

**Comment by OliAnimation** [comment]
It isn't going to get fixed, just change the file names.

**Comment by paulzikopoulos** [comment]
@OliAnimation Thanks for the answer. Is there a reason for this. I mean it used to support it. That’s not a good thing that kind of regression if you think enterprise deployment. Any ideas why not?

**Comment by TaylorSMarks** [comment]
I’m not getting a cent for this. If you’re deploying it into an enterprise environment, I made zero promises to you. Whoever chose to use it is the person who should be maintaining it. Don’t upgrade Willy-nilly in production.

Somebody else forked this into Boombox because they were frustrated with how little I’ve done with this for several years. Go ahead and switch to that.

Taylor

**Comment by paulzikopoulos** [comment]
I was more trying to get people looking at it for that kind of stuff -- but all good. I agree on the willy-nilly in production upgrade. I was just curious as to why it was an issue now and not before. But all good - thanks for building the library.

**Comment by SamwiseLA** [comment]
This allows it to work...

s_musicfile_run = "/Users/xxxxxxxxxx/Desktop/play this file.mp3" 
s_musicfile_run = s_musicfile_run.replace(" ", "%20")
playsound(s_musicfile_run)

**Comment by TechCowboy** [comment]
This is how I fixed it so I didn't need to change my existing code.
https://cowboy3398.wordpress.com/2021/01/17/playsound-fixing-an-existing-library-python-library/

**Comment by TaylorSMarks** [comment]
This is now fixed on master. I have added in a test scenario, testBlockingSPACE_MP3, which should ensure that it doesn't regress.
