### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by mixmastamyk** [TaylorSMarks/playsound#42]
I see a few good bugs and pull requests, but not touched in a while, hmm.

**Comment by TaylorSMarks** [comment]
I suppose?

It worked for my needs and it’s here to help anyone else - I figure people can fork it if they want.

I think 99% of complaints are it doesn’t work with all filenames, so my thought is “okay... so rename your file?”

There’s also complaints about the Linux implementation. I tried dealing with those years ago and quickly learned there’s no great universal way that sound is handled on Linux.

I’m open to anyone else taking over this project or whatever.

Taylor

**Comment by mixmastamyk** [comment]
Ok, so I've hacked on the code a bit and took inspiration from some of the better pull requests.  It's coming along but I think it may have changed too much to use the same project name.

**Comment by mixmastamyk** [comment]
Ok, I started over and created a new package if anyone is interested:

- https://pypi.org/project/boombox/
- https://github.com/mixmastamyk/boombox

Might still have a bug or missing feature, especially on mac os, where I've had limited time.

**Comment by TaylorSMarks** [comment]
Nice. Does your tone generator account for the equal-loudness contour, or would someone using it have to account for that if they want to ensure all tones sound the same?

Next you need to support tracker files.

Boy, this is fun to be on the demanding side rather than the side everyone sends their demands to.

**Comment by mixmastamyk** [comment]
Cross platform it uses PyAudio for tone generation.  If it supports those features I could certainly pass the appropriate parameters.  Otherwise, it supports Winsound etc, which I don't believe have any features other than presented.

Really, it is a "wrapper" module to play sound events, so I'm not expecting to do much hard-core audio processing unless someone can show me PyAudio or GST code I can cut and paste.  Event then, it might not make sense.

**Comment by mjbrusso** [comment]
I created **audioplayer**: a cross platform Python 3 package for playing sounds (mp3, wav, ogg, mid, ...). It provides the key features of an audio player, such as opening a media file, playing (loop/block), pausing, resuming, stopping, and setting the playback volume.

https://github.com/mjbrusso/audioplayer
https://pypi.org/project/audioplayer/

**Comment by TaylorSMarks** [comment]
At the urging of a friend, I have added a set of tests and set up travis-ci to run them on a few different platforms.

So... I'm now comfortable with fixing bugs myself and accepting PRs so long as they have passing tests and don't cause regressions, but I probably won't be adding any features that aren't already present.
