### ISSUE TITLE
MacOS required PyObjC

### ISSUE THREAD

**Issue by EricMyers47** [TaylorSMarks/playsound#43]
On MacOS 10.15.3 (Catalina) trying to run a simple example using Python 3.8.2 failed with: ModuleNotFoundError: No module named 'AppKit' .  More specifically:

> Traceback (most recent call last):
>   File "/Users/myers/Documents/Pioneer-LIGO/Pioneer-LIGO-2020/slot/test_playsound.py", line 6, in <module>
>     playsound.playsound("GW150914_H1_shifted.wav")
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/playsound.py", line 55, in _playsoundOSX
>     from AppKit     import NSSound
> ModuleNotFoundError: No module named 'AppKit'

A friend suggested that I use pip to install the module PyObjC, and indeed that fixed it.  Since I didn't see that suggestion in the docs I wanted to mention it.  A number of other things "broke" when I upgraded to Cataline (including no emacs!) so perhaps this is only a problem with the latest Mac environment.

**Comment by TaylorSMarks** [comment]
This is now fixed on master. I have not added PyObjC as a hard dependency, but I print out a suggestion that you aught to install it. Even without it, the code still works on Python 3 on Mac, by shelling out to Mac OS's built-in python.
