### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 2: invalid start byte

### ISSUE THREAD

**Issue by LeiYangGH** [TaylorSMarks/playsound#45]
playsound.playsound("http://dict.youdao.com/dictvoice?type=0&audio=yes")

i got 
Traceback (most recent call last):
  File "C:/NuanTools/py_tts/testonly.py", line 73, in <module>
    playsound.playsound("http://dict.youdao.com/dictvoice?type=0&audio=yes")
  File "C:\Users\YANG.LEI\AppData\Local\Continuum\anaconda3\lib\site-packages\playsound.py", line 35, in _playsoundWin
    winCommand('open "' + sound + '" alias', alias)
  File "C:\Users\YANG.LEI\AppData\Local\Continuum\anaconda3\lib\site-packages\playsound.py", line 30, in winCommand
    '\n    ' + errorBuffer.value.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 2: invalid start byte

Python 3.6.4, playsound is the latest version installed today(14th May)

**Comment by XHG78999** [comment]
(I think you are a Chinese,I am Chinese too,I will talk with you by Hanzi.)
好吧，这个库无法播放网络文件。如果需要播放，请把他下载下来后播放，再删除。（PDC WARNING：io.BytesIO不起作用）
这是目前唯一的解决办法。就连ffplay都是这么做的，简单粗暴。

**Comment by LeiYangGH** [comment]
知道了，谢谢

**Comment by TaylorSMarks** [comment]
This is now fixed on master. I have added in a test scenario, testBlockingCYRIL_WAV, which should ensure that it doesn't regress.
