### ISSUE TITLE
Add a pause/stop/seek feature

### ISSUE THREAD

**Issue by Iyxan23** [TaylorSMarks/playsound#46]
Any suggestions?

**Comment by EufranioDiogo** [comment]
I was thinking about this! Let's see if it's possible!

**Comment by EufranioDiogo** [comment]
Bro I have done this!

Now you can use playsound with a second parameter that is refered for duration in seconds it will play the sound during the amount of time you gave, but if you don't say or put anything-else it will run like the original version!

[My Fork](https://github.com/EufranioDiogo/playsound/blob/master/playsound.py)

**Comment by EufranioDiogo** [comment]
@bot-coder101  now you can see it again

**Comment by TaylorSMarks** [comment]
If you want to make a PR that adds in this feature, I'm happy to accept it as long as it doesn't add in any more dependencies or cause any regressions in the existing testcases.
