### ISSUE TITLE
File finding

### ISSUE THREAD

**Issue by Bazaer** [TaylorSMarks/playsound#49]
Hi, I have two questions.

First: Do I input the argument after playsound as a string?

e.g: 'C:\Users\******\Desktop\Music File.mp3'

And second:
What do I cut off?

xxxxxxxxxxxxxx\Desktop\Music File.mp3?

Can I have osame help with how to format the playsound command?

Sincere thank-yous in advance, Bazaer.

**Comment by TaylorSMarks** [comment]
Give either an absolute path or a relative path.
