### ISSUE TITLE
Python.org `python` on Mac OS X Requires `PyObjC` Library

### ISSUE THREAD

**Issue by riggsd** [TaylorSMarks/playsound#5]
Apple ships an old, modified version of Python with Mac OS X. Many users install upstream Python from python.org onto a Mac in order to work around old bugs.

When attempting to use playsound on Mac OS X 10.9.5 with python.org Python 2.7.12, I get the following failure:

    Traceback (most recent call last):
      File "playsound.py", line 54, in _playsoundOSX
        from AppKit import NSSound
    ImportError: No module named AppKit

This can be fixed by installing the PyObjC package (`pip install -U PyObjC`), but that pulls in a lot of compiled C modules (54 compiled .whl files on my system) and/or requires the XCode compilers.

Happily, after installing PyObjC, playsound works perfectly. But it's not quite fair to call it "Pure Python... with no dependencies" when it has C-based dependencies when using upstream Python on OS X.

**Comment by shuge** [comment]
This can be fixed by installing the PyObjC package (`easy_install --upgrade PyObjC`).

**Comment by gpraceman** [comment]
I made the mistake of trying to use pip to install AppKit.  What it installs is not what is needed.  After uninstalling that package, I ran the following command and that fixed the "No module named AppKit" error.

sudo pip install --upgrade --force-reinstall PyObjC PyObjC-core

**Comment by Burton-David** [comment]
Has, there been any updates to this issue?  My app was working fine when deployed on glcoud, but I got this error when running the files locally and tried to use "playsound"
(Using python 3.7)

**Comment by TaylorSMarks** [comment]
This is now fixed on master. I have not added PyObjC as a hard dependency, but I print out a suggestion that you aught to install it. Even without it, the code still works on Python 3 on Mac, by shelling out to Mac OS's built-in python.
