### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by ayodkay** [TaylorSMarks/playsound#54]
ModuleNotFoundError: No module named 'gi'

**Comment by acemasterjb** [comment]
@ayodkay, any context to your error, can we see the source file?

**Comment by mjlabe** [comment]
This is unrelated to this library. Are you using a raspberry pi? I've seen this error on that.

**Comment by TaylorSMarks** [comment]
I do have a pi but it’s just used as a server - I’ve never connected it to any speakers.

If I ever chose to develop a linux solution myself, I’d aim to make it work on the pi. I didn’t - the linux code in this project has always been from other people and I’ve never personally checked that it works - probably best would be to split and have several linux solutions for different distros/libraries installed.

Although it doesn’t matter - I haven’t touched playsound in several years. Use Boombox if you want something that’s actively maintained.

**Comment by mjlabe** [comment]
Thank you! You just saved me a lot of time.

**Comment by MuatazMohammed** [comment]
> Thank you! You just saved me a lot of time.
how are you solve this problem?
i face the same problem when run piece of code on ubuntu (with ROS )

**Comment by mjlabe** [comment]
Boombox actually didn't  work for me. After spending a long time figuring out what to install (because the documentation barely mentions it), it just produced static. Please share if you have a working implementation @TaylorSMarks. I ended up using omxplayer on rpi:

https://github.com/willprice/python-omxplayer-wrapper

**Comment by TaylorSMarks** [comment]
Sorry about that. I’ve never used boombox myself. I just knew the author had forked playsound and said they were going to be a better maintainer than I’ve been for the past several years.

Glad you ultimately found a solution.

**Comment by acemasterjb** [comment]
Sounddevice + Soundfile should work on all platforms.

Also, there is [Zehina's port of this project ](https://github.com/Zehina/playsound/) which has a Linux implementation (though, I think it's similar to Boombox).

**Comment by TaylorSMarks** [comment]
@acemasterjb - You are welcome to make a PR for this, assuming you add no new dependencies and don't cause any test regressions.
