### ISSUE TITLE
PlaysoundException: The file name is invalid

### ISSUE THREAD

**Issue by raffaem** [TaylorSMarks/playsound#56]
I have
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
on Windows 10.

I have installe playsound through pip.

When I try to play a sound, with as a simple filename as "sound.wav", it gives me an exception, telling the the file name is invalid:

```
>>> playsound("sound.wav")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Raffaele\anaconda3\lib\site-packages\playsound.py", line 35, in _playsoundWin
    winCommand('open "' + sound + '" alias', alias)
  File "C:\Users\Raffaele\anaconda3\lib\site-packages\playsound.py", line 31, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 304 for command:
        open "sound.wav" alias playsound_0.08730632873491562
    The filename is invalid.  Make sure the filename is not longer than 8 characters, followed by a period and an extension.
```

**Comment by acemasterjb** [comment]
Sorry to ask what might seem obvious, but is `sound.wav` in the same directory?

**Comment by raffaem** [comment]
Yes

**Comment by acemasterjb** [comment]
Don't know what to say, works for me assuming you've initialised playsound like this

```
from playsound import playsound
``` 

before calling

```
playsound("sound.wav")
```

You can always ensure you're using the directory you want to read the file from like this

```
from os import chdir
from playsound import playsound

chdir("C:\path\to\file")

# then calling the playsound method
playsound("sound.wav")
```

This will always work

**Comment by TaylorSMarks** [comment]
I assume this is fixed on master now. Please make a PR demonstrating the issue in test.py if this is not the case.
