### ISSUE TITLE
Version 

### ISSUE THREAD

**Issue by obliviousmonkey1** [TaylorSMarks/playsound#58]
Quick question. Does this work for 3.9

**Comment by notbored** [comment]
Quick answer: Yes.

Would of been quicker to install and test it out than to raise an issue.

**Comment by TaylorSMarks** [comment]
Yes, I have travis-ci verifying that all tests pass on Python 3.9 on both macOS 11.3 (Big Sur) and Windows Server 2016 (although I kind of cheat on Windows by using a mock/patch since it's a headless server without any audio drivers...)
