### ISSUE TITLE
play speed

### ISSUE THREAD

**Issue by sina-rostami** [TaylorSMarks/playsound#60]
are there any options to control the playing speed with `playsound` ?

**Comment by acemasterjb** [comment]
`self.winCommand(f'set speed 0.5 alias', self.alias)`

https://docs.microsoft.com/en-us/windows/win32/multimedia/set

> The set command establishes control settings for the device. CD audio, digital-video, MIDI sequencer, VCR, videodisc, video-overlay, and **waveform-audio devices recognize this command**.

> speed factor
> Sets the relative speed of video and audio playback from the workspace. Factor is the ratio between the nominal frame rate and the desired frame rate, where the nominal frame rate is designated as 1000.

**Comment by TaylorSMarks** [comment]
If you want to make a PR that adds in this feature, I'm happy to accept it as long as it doesn't add in any more dependencies or cause any regressions in the existing testcases.
