### ISSUE TITLE
not working with my audio jack

### ISSUE THREAD

**Issue by naga-master** [TaylorSMarks/playsound#61]
while using below function the audio is not playing with my audio jack. even output speaker is selected to audio jack in WINDOWS 10
```
playsound(path) 
```

**Comment by Sandwich1699975** [comment]
It works for me.  
Please specify more information

**Comment by TaylorSMarks** [comment]
If you want to make a PR that adds in this feature, I'm happy to accept it as long as it doesn't add in any more dependencies or cause any regressions in the existing testcases.
