### ISSUE TITLE
    Cannot find the specified file.  if the name in Arabic characters 

### ISSUE THREAD

**Issue by ahmedyasserays** [TaylorSMarks/playsound#63]
while trying to use the library in my humble code I got this error saying "can't find specified file" so after some tries noticed that it worked file with files names in English but have problems with the Arabic characters ... hope I've made it obvious enough

**Comment by TaylorSMarks** [comment]
This is now fixed on master. I have added in a test scenario, testBlockingCYRIL_WAV, which should ensure that it doesn't regress.
