### ISSUE TITLE
playsound("path_to_file.wav") causes memory leak

### ISSUE THREAD

**Issue by ulucsahin** [TaylorSMarks/playsound#66]
Hello,

I have a system that runs continuously for hours. I realized that memory usage is increasing over time and found out that removing playsound(...) calls solves the issue. When I tested calling playsound method in a while loop I saw a fast increase in memory usage over time. I am guessing this is a bug.

**Comment by LeNarvalo** [comment]
Same for me.

**Comment by TaylorSMarks** [comment]
Please add a failing test case to test.py in a PR to demonstrate the issue, if it still exists. If you had found this on Windows, I suspect that I've since fixed it, though.

**Comment by frakman1** [comment]
@TaylorSMarks would you mind pointing me to the Windows fix?

**Comment by TaylorSMarks** [comment]
@frakman1 - Version 1.3.0, released in July, should have the fix. This issue was reported in April. As I stated when closing this, I believe it was fixed in that release.
