### ISSUE TITLE
pyinstaller

### ISSUE THREAD

**Issue by Pinball3D** [TaylorSMarks/playsound#73]
when i use pyinstaller i get the error "no module named playsound"

**Comment by TaylorSMarks** [comment]
Hello,

I'm not familiar with pyinstaller. I would think you should report this to them, not me - here's their page:

https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

I'll close this now since it doesn't really sound like a bug in playsound to me.
