### ISSUE TITLE
Windows MCI Gets in a bad State: "cannot specify extra characters after a string enclosed in quotation marks."

### ISSUE THREAD

**Issue by TaylorSMarks** [TaylorSMarks/playsound#75]
Periodically, Windows MCI gets into a bad state and just repeatedly returns the error message "cannot specify extra characters after a string enclosed in quotation marks."

I cannot find a way to reliably put MCI into this state. It seems that it most often (always?) begins when running the test testBlockingSPACE_MP3. But this isn't consistent it can sometimes run this test several times in a row without an issue. After the issue has occurred the first time, I believe the issue is cached, so that the exact command cannot be run again afterwards.

I find that sometimes it's worse than just the exact command - it seems the "bad state" ends up spreading to trying to open/play other files which are otherwise reliably okay after the initial failure.

Once the "bad state" starts, I have not found a way to fix it. It persists between restarts of Python and the command line. Restarting windows reliably fixes it. I've found that waiting some time (I'm not sure how long. Five minutes?) seems to fix the issue.

Without knowing how to reliably start or stop this issue, it's difficult to know how to test whether it's actually fixed or not. I suspect the issue stems from some combination of spaces, quotes, and parenthesis.

It's difficult to test this on Travis-CI as it doesn't actually have MCI, and so we're using mocks/patches there instead. I might try switching to GitHub actions and seeing if I can use a real MCI there.

**Comment by TaylorSMarks** [comment]
The filename being longer than 8.3 might also contribute to this error occurring?

I'm not sure - I've changed the unit tests when running on Travis-CI on Windows to call the real MCI, but as I haven't been able to install the drivers, they all have error messages about stuff missing... I patch those out in the tests, but should the error about missing quotes (error code 305) appear, the tests will still fail.

**Comment by Numerlor** [comment]
I've looked into this a bit after I got the error (consistently) locally with paths that had backslashes and were quoted as a consequence, letting ctypes handle the argument conversion after specifying argtypes on the mci functions seems to work; I can open a PR if you'd like.

**Comment by TaylorSMarks** [comment]
Yes, open a PR. If Travis CI is clean on your PR I’ll merge it and push it to Pypi.

You can comment out the one Ubuntu config that keeps timing out after 10 minutes. I haven’t been able to find out what’s happening with it.

Thanks,
Taylor

**Comment by cool-RR** [comment]
Is this issue related to this problem: https://stackoverflow.com/questions/68518657/what-is-problem-in-this-python-code-cannot-specify-extra-characters-after-a-str

I had the same problem described in the SO question happen to me. I downgraded like the first solution suggests, and the problem went away. Is this the correct bug for that problem? Note that this SO question is highly active, and ten people upvoted the answer. This must be happening to a lot of people right now.

**Comment by Numerlor** [comment]
> Is this issue related to this problem: https://stackoverflow.com/questions/68518657/what-is-problem-in-this-python-code-cannot-specify-extra-characters-after-a-str
> 
> I had the same problem described in the SO question happen to me. I downgraded like the first solution suggests, and the problem went away. Is this the correct bug for that problem? Note that this SO question is highly active, and ten people upvoted the answer. This must be happening to a lot of people right now.

Yes, I believe that is the problem that is solved by the PR that closed the issue

**Comment by cool-RR** [comment]
But this issue is from over a year ago, while the current problem is ongoing.

**Comment by Numerlor** [comment]
A release with the changes hasn't been made yet, as for getting that done, you'll have to ask @TaylorSMarks

**Comment by cool-RR** [comment]
@TaylorSMarks What do you think about that?

**Comment by TaylorSMarks** [comment]
I release so infrequently I forget how to do it everytime.

I also think there’s some new signing thing you’re supposed to do now when uploading to pypi…

Personally, I use pip to install stuff from git a lot… you could just do that for this.

Or I could look into uploading a new version to pypi…

**Comment by cool-RR** [comment]
I recommend making a new release. Many people are frustrated by this bug. Yes, I could `pip install` from GitHub but people don't want to depend on a non-released version.

I maintain a few packages on PyPI and I don't think the signing thing came into effect yet.
