### ISSUE TITLE
troubleshooting strange error occurrences

### ISSUE THREAD

**Issue by JMA6971** [TaylorSMarks/playsound#83]
After moving code from windows10 mach to 2nd windows10 mach, but python ver 3.7.3 to python 3.9.5, working code now has error:
`\miniconda3\lib\site-packages\playsound.py in _playsoundWin(sound, block)
     71         logger.debug('Starting')
     72         winCommand(u'open {}'.format(sound))
---> 73         winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))
     74         logger.debug('Returning')
     75     finally:

~\miniconda3\lib\site-packages\playsound.py in winCommand(*command)
     62                                 '\n    ' + errorBuffer.raw.decode('utf-16').rstrip('\0'))
     63             logger.error(exceptionMessage)
---> 64             raise PlaysoundException(exceptionMessage)
     65         return buf.value
     66 

PlaysoundException: 
    Error 259 for command:
        play .. file.mp3 wait
    The driver cannot recognize the specified command parameter.`

also seemingly random cases of error 263:

`~\miniconda3\lib\site-packages\playsound.py in _playsoundWin(sound, block)
     70     try:
     71         logger.debug('Starting')
---> 72         winCommand(u'open {}'.format(sound))
     73         winCommand(u'play {}{}'.format(sound, ' wait' if block else ''))
     74         logger.debug('Returning')

~\miniconda3\lib\site-packages\playsound.py in winCommand(*command)
     62                                 '\n    ' + errorBuffer.raw.decode('utf-16').rstrip('\0'))
     63             logger.error(exceptionMessage)
---> 64             raise PlaysoundException(exceptionMessage)
     65         return buf.value
     66 

PlaysoundException: 
    Error 263 for command:
        open .file.mp3
    The specified device is not open or is not recognized by MCI.`

**Comment by JMA6971** [comment]
oddly, although this program setup continuously has random errors, I can loop through all the sound files and play them successfully.  Once out of several tries playing 30 short .mp3, there was an error.  Here is code that has errors :
`import re 
from playsound import playsound
from sounds import *
import time

def follow(thefile):    
    while True:
        line = thefile.readline()
        time.sleep(3)
        yield line
for line in loglines:
    match=re.findall(r'\b[A-Z]{2,}\b', line)
    s=match[1]
    playsound('../Python_Scripts/' + sounds[s])
    print(line)`

**Comment by JMA6971** [comment]
can't tell if this is an issue with the machine, or because of the python update.  one thing to try would be update the python on working machine and see if same errors pop up.

**Comment by TaylorSMarks** [comment]
It’s possible it’s because you had different versions of playsound.

The version on the master branch is slightly newer than what’s on pypi and may have fixed the issue. Can you use the master branch and let me know if the issue still persists?

If the issue is resolved, I’ll push from master to pypi.

Taylor

**Comment by JMA6971** [comment]
Taylor,

Hi, thanks for getting right back.  I have 1.3 on the new machine...and that is the setup with errors.  I have 1.2.2 on the old machine that has run fine for a couple years.  Maybe I'll try downgrading to 1.2.2 on the new machine.

Best,
Jon

**Comment by JMA6971** [comment]
YES!!  Thanks for getting me in the right direction. Downgrade to 1.2.2 solved issue.

**Comment by l13rb4git** [comment]
I was getting the error `The specified device is not open or is not recognized by MCI.` when the print statements were added to my little script: 

```python
from time import sleep
from playsound import playsound


def main():
    inspiration = 3
    expiration = 1
    hold_on_full = 1
    hold_on_empty = 1

    sleep(expiration)
    bell()

    while True:
        for _ in range(10):
            print("Inspire")
            sleep(inspiration)
            print("Hold")
            bell()
            sleep(hold_on_full)
            print("Expire")
            bell_longer()
            sleep(expiration)
            print("Rest")
            bell()
            sleep(hold_on_empty)
            bell()

        hold_on_full += 1
        hold_on_empty += 0.5
        expiration += 0.25



def bell():
    playsound('bell.mp3')


def bell_longer():
    playsound('bellbass.mp3')



if __name__ == "__main__":
    main()
```

Thankfully, downgrade to 1.2.2 solved issue.
