### ISSUE TITLE
Close the file handle after playing it on Windows

### ISSUE THREAD

**Issue by 42RK** [TaylorSMarks/playsound#9]
I believe `winCommand('close "' + sound + '" alias', alias)` should be added after the 38th line.

The module at its current state doesn't allow programs to play a file, remove it, save one with the same filename and repeat, unlike mp3play.

**Comment by wannaphongcom** [comment]
https://github.com/TaylorSMarks/playsound/pull/10

**Comment by mkmoisen** [comment]
@TaylorSMarks would you please merge this branch?

**Comment by TaylorSMarks** [comment]
This is now fixed on master. I have added in a test scenario, testNonBlockingRepeat, which should ensure that it doesn't regress.
