### ISSUE TITLE
Having `block=True` by default is not good

### ISSUE THREAD

**Issue by PedanticHacker** [TaylorSMarks/playsound#96]
I don't know why the `block` argument to the `playsound.playsound()` function is set to `True` by default.

I must set it to `False` just to have asynchronous playing of a sound out-of-the-box, otherwise I have a bad experience and the sound is very laggy. This should change. And if anyone would have issues by the `block` argument now being set to `False` by default (not likely, but okay), one could easily set this `block` argument to `True`. That's the way it should be from the beginning, having `block=False` by default (not the other way around).

I'm beginning to wonder why is the `block` argument needed at all. Are people really having so much issues playing a sound asynchronously that this `block` argument, first of all, exists and, second of all, is set to `True` by default?

**Comment by ddmee** [comment]
What platform are you on? It seems weird that you'd get a difference in the sound if you set block=True. That seems more like a bug that whether the default blocking default is true or false.

**Comment by PedanticHacker** [comment]
@ddmee, I'm on Windows 10.

**Comment by PedanticHacker** [comment]
I'm now also getting this error message in playsound version 1.3.0 on Windows 10 (having the `block` argument set to `False`).
```
Error 263 for command:
        close source/backend/sound/files/black-move.wav
    The specified device is not open or is not recognized by MCI.
Failed to close the file: source/backend/sound/files/black-move.wav
```
The sound plays, but this error message appears in the console. It does not crash my application, just this error message appears. 

But if I leave the `block` argument to its default `True` value, I get no such error message, then I just experience a 1 second lag and the playing of the WAV sound.

Can anyone investigate this? The lag is very annoying.
